[project]
name = "linakdeskapp"
version = "1.0.1"
description = "Desktop application that allows control of Linak office desks under Linux"
keywords = ["Linak", "electric desk", "Bluetooth"]
readme = "README.md"
license = "MIT"
license-files = ["LICENSE"]
authors = [
    ## separate 'name' and 'email' hack to fill "Author:" and "Author-email:" fields
    { name = "Arkadiusz Netczuk" }, { email = "dev.arnet@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "PyQt5",
    "matplotlib",
    "pandas",
    "bluepy>=1.0.5",
    "LinakDPGBt @ git+https://github.com/anetczuk/linak_bt_desk.git",
]

[project.urls]
Homepage = "https://github.com/anetczuk/LinakDeskApp"
Repository = "https://github.com/anetczuk/LinakDeskApp"

[project.optional-dependencies]
dev = [
    ### dependencies for "tools" scripts

    "xmltodict",    ## for mdpreproc.py

    "pycodestyle",
    "flake8",
    "pydocstyle",
    "coverage",             ## for coverage.sh
    "mdlinkscheck",

    ## for profiling (tools/profiler.sh)
    "pyprof2calltree",   
    "snakeviz",
    "mtprof",
    "viztracer",
]

[project.scripts]
linakdeskapp = "linakdeskapp.main:main"
linakdeskctl = "linakdeskapp.main:main"

[tool.setuptools]
package-dir = { "" = "src" }

[tool.setuptools.packages.find]
where = ["src"]
include = ["linakdeskapp*", "linakdeskmock*"]

[tool.setuptools.package-data]
linakdeskapp = [
    "ui/*.ui",
    "gui/img/*.png",
]

[build-system]
requires = ["setuptools>=77", "wheel"]
build-backend = "setuptools.build_meta"
