#!/bin/bash

set -e


## works both under bash and sh
SCRIPT_DIR=$(dirname "$(readlink -f "$0")")


cd $SCRIPT_DIR

python3 -m linakdeskapp "$@"

exit_code=$?


if [ $exit_code -ne 0 ]; then
    echo "abnormal application exit: $exit_code"
fi

